version: "3"
services:
  app:
    container_name: web
    build: .
      image: ${DOCKER_USER_ID}/flask
production:
    image: ${DOCKER_USER_ID}/flask:${BUILD_NUMBER}
    volumes: 
        - .:/app
    ports:
        - 3000:3000
