version: "3"
services:
  app:
     build: .
     image: ${DOCKER_USER_ID}/flask
  production:
     image: ${DOCKER_USER_ID}/flask:${BUILD_NUMBER}
     ports:
         - 3000:3000
     volumes: 
         - .:/app
         
