version: "3" 
services: 
  app: 
    container_name: web 
    build: 
      context: . 
    image: ${DOCKER_USER_ID}/vue 
  production: 
    image: ${DOCKER_USER_ID}/vue:${BUILD_NUMBER} 
    volumes: 
      - .:/app
    ports: 
      - 3000:3000
